name: Run Cypress Tests and Generate Mochawesome Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Install dependencies
        run: npm ci

      - name: Add node_modules/.bin to PATH
        run: echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH

      - name: Reinstall Cypress
        run: npx cypress install --force

      - name: Create reports directory
        run: mkdir -p cypress/reports/html/.jsons

      - name: Run Cypress tests
        run: |
          ./node_modules/.bin/cypress run \
          --reporter mochawesome \
          --reporter-options "reportDir=cypress/reports/html/.jsons,overwrite=false,html=false,json=true"

      - name: Debug generated JSON reports
        run: ls -l cypress/reports/html/.jsons

  - name: Upload Mochawesome reports
  uses: actions/upload-artifact@v3
  with:
    name: mochawesome-reports
    path: cypress/reports/html/
