name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Limpar cache do Cypress para evitar problemas de download
      - name: Clear Cypress cache
        run: npx cypress cache clear

      # Instalar Cypress manualmente
      - name: Install Cypress
        run: npx cypress install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run ui-regression

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30
