name: Testes Cypress
on:
  push:
    branches:
      - main
      - master

jobs:
  cypress-run-chrome:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
      uses: actions/setup-node@v4
      with:
       node-version: 22.12.0
      
      - name: Install dependencies
        run: npm install # Ou yarn install se você usa yarn
        
      - name: Criar diretórios para videos e screenshots
        run: |
          mkdir -p cypress/videos
          mkdir -p cypress/screenshots

      - name: Cypress.io rodando testes chrome
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --browser chrome

      - name: Prints da execução de testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots-chrome
          path: cypress/screenshots
          retention-days: 1

      - name: Vídeos da execução de testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-chrome
          path: cypress/videos
          retention-days: 1