name: Testes Cypress

on:
  push:
    branches:
      - main
      - master

jobs:
  cypress-run-chrome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Instalar dependências do projeto
        run: |
          npm ci
          npx cypress install

      - name: Corrigir permissões do Cypress
        run: chmod +x ./node_modules/.bin/cypress

      - name: Verificar a instalação do Cypress
        run: npx cypress verify

      - name: Executar testes Cypress no Chrome
        run: npm run cy:run:chrome

      - name: Esperar 30 segundos para garantir que os relatórios sejam gerados
        run: sleep 30

      - name: Listar arquivos para verificar os relatórios
        run: |
          echo "Conteúdo do diretório cypress/reports/html"
          ls -l cypress/reports/html

      - name: Fazer upload de capturas de tela
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots-chrome
          path: cypress/screenshots
          retention-days: 1

      - name: Fazer upload de vídeos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-chrome
          path: cypress/videos
          retention-days: 1

      - name: Fazer upload do relatório Mochawesome (JSON)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mochawesome-report-json
          path: cypress/reports/html/.jsons/*.json
          retention-days: 1

      - name: Fazer upload do relatório Mochawesome (HTML)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mochawesome-report-html
          path: cypress/reports/html/*.html
          retention-days: 1
