name: Cypress Tests

on:
  schedule:
    - cron: '0 8 * * *'  # Executa todos os dias às 08:00 UTC (09:00 em Portugal)
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Usando versão LTS estável
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run ui-regression

      - name: Get current DATE
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cypress-Origination-Report-${{ env.DATE }}
          path: cypress/reports/html
          retention-days: 7

      - name: Deploy Mochawesome report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages