name: Cypress Tests

on:
  schedule:
    - cron: '0 8 * * *'  # Executa todos os dias às 08:00 UTC (09:00 em Portugal)
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Get current DATE
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # ORIGINATION
      - name: Run Cypress tests - Origination
        run: |
          rm -rf cypress/reports/html
          npx cypress run --spec "cypress/e2e/!(Collections*)*.cy.js"

      - name: Upload artifact - Origination
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cypress-Origination-Report-${{ env.DATE }}
          path: cypress/reports/html
          retention-days: 7

      # COLLECTIONS
      - name: Run Cypress tests - Collections only
        run: |
          rm -rf cypress/reports/html
          npx cypress run --spec "cypress/e2e/Collections*.cy.js"

      - name: Upload artifact - Collections
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cypress-Collections-Report-${{ env.DATE }}
          path: cypress/reports/html
          retention-days: 7