name: Testes Cypress

on:
  push:
    branches:
      - main
      - master

jobs:
  cypress-run-chrome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Instalar dependências do projeto
        run: |
          npm ci
          npx cypress install # Garante que o Cypress seja baixado corretamente

      - name: Corrigir permissões do Cypress
        run: chmod +x ./node_modules/.bin/cypress

      - name: Verificar a instalação do Cypress
        run: npx cypress verify

      - name: Criar diretórios para artefatos de teste
        run: |
          mkdir -p cypress/videos
          mkdir -p cypress/screenshots

      - name: Executar testes Cypress no Chrome
        run: npm run cy:run:chrome # Usa o script definido no package.json

      - name: Fazer upload de capturas de tela
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots-chrome
          path: cypress/screenshots
          retention-days: 1

      - name: Fazer upload de vídeos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-chrome
          path: cypress/videos
          retention-days: 1
