name: Run Cypress Tests and Generate Mochawesome Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Install dependencies
        run: npm ci

      - name: Create directories for reports and screenshots
        run: |
          mkdir -p cypress/reports/json
          mkdir -p cypress/screenshots

      - name: Reinstall Cypress
        run: npx cypress install --force

      - name: Run Cypress tests
        run: |
          ./node_modules/.bin/cypress run \
          --reporter mochawesome \
          --reporter-options "reportDir=cypress/reports/json,overwrite=false,json=true"

      - name: List reports directory
        run: ls -lR cypress/reports/

      - name: Upload Mochawesome reports
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-reports
          path: cypress/reports/json/

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots/
